env:
  browser: true
  node: true
  es2021: true

parser: 'vue-eslint-parser'

parserOptions:
  parser: '@typescript-eslint/parser'

ignorePatterns:
  - ./node_modules
  - ./dist

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/vue3-recommended'
  - 'prettier'

plugins:
  - '@typescript-eslint'
  - 'vue'
  - 'prettier'

rules:
  'prettier/prettier': ['error']
